name: Hap 编译

on:
  push:
    branches: [ "gui" ]
  pull_request:
    branches: [ "gui" ]
  release:
    types: [ published ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: 设置复用变量
        id: strings
        shell: bash
        run: |
          if [ "${{ github.event_name }}" == "release" ]; then
            VERSION="${{ github.event.release.tag_name }}"
          else
            VERSION="$(git rev-parse --short HEAD)"
          fi
          echo "archieve-hap-name=spiration-$VERSION-openharmony"
          echo "build-output-hap=${{ github.workspace }}/ohos/entry/build/default/outputs/default/entry-default-unsigned.hap"
      
      - name: 编译项目
        uses: CoolCLK/build-haps@v1
        with:
          folder: ${{ github.workspace }}/ohos

      - name: 上传工件
        if: github.event_name != 'release'
        uses: actions/upload-artifact@v6
        with:
          name: ${{ steps.strings.outputs.archieve-hap-name }}
          path: ${{ steps.strings.outputs.build-output-hap }}

      - name: 上传到 GitHub Release
        if: github.event_name == 'release'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: >
          gh release upload ${{ github.event.release.tag_name }}
          "${{ steps.strings.outputs.build-output-hap }}#${{ steps.strings.outputs.archieve-hap-name }}.hap"
          --repo ${{ github.repository }}
